services:
  catfood_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: catfood
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
